# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteDashApp', '0002_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='posted_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='QuoteDashApp.Users'),
            preserve_default=False,
        ),
    ]
